/*
 * Copyright (C) ExBin Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.exbin.utils.guipopup.panel;

import java.awt.Component;
import java.awt.event.ActionListener;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import org.exbin.utils.guipopup.LanguageUtils;

/**
 * Inspection panel for GUI component.
 *
 * @version 0.1.0 2019/07/22
 * @author ExBin Project (http://exbin.org)
 */
public class InspectComponentPanel extends javax.swing.JPanel {

    private final java.util.ResourceBundle resourceBundle = LanguageUtils.getResourceBundleByClass(InspectComponentPanel.class);

    private final ComponentParentsListModel componentParentsListModel = new ComponentParentsListModel();
    private final PropertyTablePanel propertyTablePanel = new PropertyTablePanel();
    private Object component;
    private int currentlyShown = 0;

    public InspectComponentPanel() {
        initComponents();
    }

    public void setComponent(Object component, String componentName) {
        this.component = component;

        componentClassTextField.setText(componentName == null ? "-" : componentName);
        parentsList.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int selectedIndex = parentsList.getSelectedIndex();
                if (selectedIndex >= 0 && currentlyShown != selectedIndex) {
                    currentlyShown = selectedIndex;
                    Object itemObject = componentParentsListModel.getItemObject(currentlyShown);
                    propertyTablePanel.setObject(itemObject);
                }
            }
        });

        updateParentsList();

        propertyTablePanel.setObject(component);
        splitPane.setBottomComponent(propertyTablePanel);
    }

    private void updateParentsList() {
        componentParentsListModel.clear();

        componentParentsListModel.add(getClassName(component.getClass()), component);
        if (component instanceof Component) {
            Component comp = ((Component) component).getParent();
            while (comp != null) {
                String name = getClassName(comp.getClass());
                componentParentsListModel.add(name, comp);
                comp = comp.getParent();
            }
        }
    }

    private String getClassName(Class<?> clazz) {
        String name = clazz.getCanonicalName();
        if (name == null) {
            name = clazz.getTypeName();
            if (name == null) {
                name = "<anonymous>";
            }
        }

        return name;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        splitPane = new javax.swing.JSplitPane();
        parentsListScrollPane = new javax.swing.JScrollPane();
        parentsList = new javax.swing.JList<>();
        componentLabel = new javax.swing.JLabel();
        componentClassTextField = new javax.swing.JTextField();
        closeButton = new javax.swing.JButton();
        showStaticFieldsCheckBox = new javax.swing.JCheckBox();

        splitPane.setDividerLocation(230);

        parentsList.setModel(componentParentsListModel);
        parentsList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        parentsListScrollPane.setViewportView(parentsList);

        splitPane.setLeftComponent(parentsListScrollPane);

        componentLabel.setText(resourceBundle.getString("componentLabel.text")); // NOI18N

        componentClassTextField.setEditable(false);

        closeButton.setText(resourceBundle.getString("closeButton.text")); // NOI18N

        showStaticFieldsCheckBox.setText(resourceBundle.getString("InspectComponentPanel.showStaticFieldsCheckBox.text")); // NOI18N
        showStaticFieldsCheckBox.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                showStaticFieldsCheckBoxStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 740, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(componentLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(componentClassTextField))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(showStaticFieldsCheckBox)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(closeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(componentLabel)
                    .addComponent(componentClassTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(splitPane, javax.swing.GroupLayout.DEFAULT_SIZE, 367, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(closeButton)
                    .addComponent(showStaticFieldsCheckBox))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void showStaticFieldsCheckBoxStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_showStaticFieldsCheckBoxStateChanged
        propertyTablePanel.setShowStaticFields(showStaticFieldsCheckBox.isSelected());
        Object itemObject = componentParentsListModel.getItemObject(currentlyShown);
        propertyTablePanel.setObject(itemObject);
    }//GEN-LAST:event_showStaticFieldsCheckBoxStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton closeButton;
    private javax.swing.JTextField componentClassTextField;
    private javax.swing.JLabel componentLabel;
    private javax.swing.JList<String> parentsList;
    private javax.swing.JScrollPane parentsListScrollPane;
    private javax.swing.JCheckBox showStaticFieldsCheckBox;
    private javax.swing.JSplitPane splitPane;
    // End of variables declaration//GEN-END:variables

    public void setCloseActionListener(ActionListener listener) {
        closeButton.addActionListener(listener);
    }
}
